# Generated by Django 4.1.1 on 2022-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IISapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_end',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_start',
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrátor'), (2, 'Pečovatel'), (3, 'Veterinář'), (4, 'Dobrovolník')], default=4),
        ),
    ]
