# Generated by Django 4.1.1 on 2022-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IISapp', '0007_alter_animal_image_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='profile_pic_default.jpg', upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pic_default.jpg', upload_to='static/img'),
        ),
    ]
