# Generated by Django 4.1.1 on 2022-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IISapp', '0013_alter_outing_reservation_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='profile_pic_default.jpg', null=True, upload_to='static/img'),
        ),
    ]
