# Generated by Django 4.1.1 on 2022-10-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IISapp', '0015_alter_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='outing_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IISapp.outing_reservation'),
        ),
    ]
