# Generated by Django 4.1.1 on 2022-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0002_remove_record_record_end_remove_record_record_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numb',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
