# Generated by Django 4.1.1 on 2022-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing_reservation',
            name='outing_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
