# Generated by Django 4.1.1 on 2022-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
