# Generated by Django 4.1.1 on 2022-10-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing_reservation',
            name='user_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
