# Generated by Django 4.1.1 on 2022-10-22 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IISapp', '0016_requests_outing_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solver_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
