# Generated by Django 4.1.1 on 2022-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0017_alter_requests_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_verification',
            field=models.BooleanField(default=False),
        ),
    ]
