# Generated by Django 4.1.1 on 2022-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisapp', '0020_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
